spring:
  datasource:
    #    url: jdbc:mysql://localhost:3306/mall_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: root
    url: jdbc:mysql://139.129.226.213:3306/mall_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://139.129.226.213:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zenith1124@
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    #    host: 47.93.55.96 # Redis服务器地址 192.168.31.254
    host: localhost # Redis服务器地址
    #    host: 192.168.31.254 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  mail:
    host: smtp.exmail.qq.com
    username: bjlc@qhlnsj.com
    password: B3brLyUNhgZA6Amo
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          timeout: 25000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
logging:
  level:
    root: info
    com.zenithchain.mall: debug
  file:
    path: admin
logstash:
  host: localhost

express:
  kuaidi100:
    #    key: RgDeJzpK2956
    #    customer: 0E13FD43920A7ACB95A0FBE7F1AD6A17
    #    secret: 707d6897543141cebfae7ba2382693fe
    #    userid: a68e7462fe534b49a0702a97859ba066
    key: tOoztaEW6976
    customer: 0C77EF3E75128847C7E3ACDAB8B7C451
    secret: bda0983cf1c248bd873a5d4d3fda27c8
    userid: 709584418bd24be4896b6abd11779631

